name: "Setup module environment"
description: "Sets up environment for module"

inputs:
    go_version:
      description: "go version"
      required: false
      default: '1.19.0'

runs:
  using: "composite"
  steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up go environment
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go_version }}
